### ISSUE TITLE
Quckstart missing historian configuration

### ISSUE THREAD

**Issue by craig8** [eclipse-volttron/volttron-core#127]
**Describe the bug**
The QUICKSTART.md file does not include a configuration for the historian it should be as follows.

```yml
connection:
  # type should be sqlite
  type: sqlite
  params:
    # Relative to the agents data directory
    database: "data/historian.sqlite"
```
